// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpfhatpademhbcbrqtch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZmhhdHBhZGVtaGJjYnJxdGNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNDQ2NTAsImV4cCI6MjA4MjYyMDY1MH0.sqyyOnHxjnVFrL-gD7SKWfBuj6b6DCG25M4K7r_xrns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});