/**
 * Stub type declarations for React Router v7 auto-generated +types modules.
 * These are normally generated by `react-router typegen` during dev,
 * but we provide stubs so TypeScript doesn't error during CI/Vercel builds.
 */
declare module "*/+types/*" {
  import type { MetaFunction, LinksFunction } from "react-router";

  export namespace Route {
    type MetaArgs = {
      data?: any;
      params: Record<string, string>;
      location: { pathname: string; search: string; hash: string };
      matches: any[];
    };

    type LinksFunction = LinksFunction;

    type LoaderArgs = {
      request: Request;
      params: Record<string, string>;
      context?: any;
    };

    type ActionArgs = {
      request: Request;
      params: Record<string, string>;
      context?: any;
    };

    type ComponentProps = {
      loaderData: any;
      actionData?: any;
      params: Record<string, string>;
      matches?: any[];
    };

    type ErrorBoundaryProps = {
      error: unknown;
    };
  }
}
